DEBUG: False
HEURISTICS:
  LARGE_PC: 500000
  PLANE_SIZE: 16000
  VOXEL_SIZE: 0.01

THRESH: 0.025

OUT_REMOVAL:
  Use: True
  STATS:
    NB_NEIGHBORS: 3000
    STD_RATIO: 0.3
  # GEOMETRY:
  #   NB_POINTS: 16
  #   RADIUS: 0.05


