N_PLANES: 7
DEBUG: False

THRESH: 0.03

DOWN_SAMPLING:
  USE: False
  VOXEL_SIZE: 0.02

OUT_REMOVAL:
  STATS:
    USE: True
    NB_NEIGHBORS: 3000
    STD_RATIO: 0.3
  GEOMETRY:
    USE: False
    NB_POINTS: 16
    RADIUS: 0.05
