DEBUG: True
VERBOSE: False
# set 'test' for debugging or 'raw' for production
DATASET: 'raw'
HEURISTICS:
  PLANE_SIZE: 10000
  # bring pointcloud into scope
  LARGE_PC: 750000
  VOXEL_SIZE: 0.025
  VOXEL_STEP: 0.0025

# Hyperparameter for the RANSAC algorithm
THRESH: 0.03

RAW_REMOVAL:
  USE: True
  THRESH: 0.05

OUT_REMOVAL:
  USE: True
  STATS:
    NB_NEIGHBORS: 100
    STD_RATIO: 0.5



