DEBUG: True
HEURISTICS:
  LARGE_PC: 750000
  PLANE_SIZE: 10000
  VOXEL_SIZE: 0.025

THRESH: 0.03

OUT_REMOVAL:
  Use: False
  STATS:
    NB_NEIGHBORS: 3000
    STD_RATIO: 0.3
  GEOMETRY:
    NB_POINTS: 16
    RADIUS: 0.05


