DEBUG: True
VERBOSE: False
# set 'test' for debugging or 'raw' for production
DATASET: 'raw'
HEURISTICS:
  # minimal number of points considered for a plane
  PLANE_SIZE: 12000
  # point cloud downsampling
  LARGE_PC: 750000
  VOXEL_SIZE: 0.025
  VOXEL_STEP: 0.0025

# hyperparameter for the RANSAC algorithm
THRESH: 0.03

# remove planes from original point cloud data
PLANE_REMOVAL:
  USE: True
  THRESH: 0.05

OUT_REMOVAL:
  USE: True
  # Up to know, only 'StatisticalOutlierRemoval' or 'RadiusOutlierRemoval' are available
  METHOD: 'StatisticalOutlierRemoval'
  NB_NEIGHBORS: 100
  STD_RATIO: 2.0



