DEBUG: True
HEURISTICS:
  LARGE_PC: 750000
  PLANE_SIZE: 10000
  VOXEL_SIZE: 0.025
  VOXEL_STEP: 0.0025

THRESH: 0.03

OUT_REMOVAL:
  USE: True
  STATS:
    NB_NEIGHBORS: 3000
    STD_RATIO: 0.3

RAW_REMOVAL:
  USE: True
  THRESH: 0.05



